# docker-compose.yml
version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    
    # *** 關鍵修改：新增 --trace 參數 ***
    # 使用 8888 埠口，並加入 --trace 參數
    command: jekyll serve --watch --force_polling --drafts --host 0.0.0.0 --trace 

    ports:
      - "8888:4000" # 請確保您使用一個未保留的埠口

    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle